#!/usr/bin/env bash
#This script installs nginx
# Install nginx

apt-get update-y
apt-get install neginx-y
sudo ufw allow 'Nginx HTTP'
sh-c 'eco "Hello world!" >/var/www/html/indx.html'
service neginx restart

