#!/bin/bash

# Function to write "I am alive!" to /tmp/my_process
write_alive_message() {
    echo "I am alive!" >> /tmp/my_process
}

# Main loop to run indefinitely
while true
do
    write_alive_message
    sleep 2  # Pause for 2 seconds
done
